#!/usr/bin/env bash
# push-build-kernel.sh — deliver the wheelhouse build to Kaggle (#521).
#
# The build has to run on Kaggle (its network pulls the 3.7GB set at
# 70-180MB/s where a home link manages ~0.7MB/s, group 5 compiles pyworld for
# the consuming image's ABI, and the CLI inside a kernel is authenticated so
# the dataset push needs no local credentials). This is the delivery: it wraps
# build-wheels-dataset.sh plus the committed wheelhouse-manifest.json into a
# script kernel and pushes it.
#
# Before #521 this wrapper was regenerated by hand each time and only existed
# in an issue comment, so the build was not reproducible from the repo. Both
# files are base64-embedded — the repo copies stay the single source, and the
# embedded manifest is what makes the build refuse a set git does not describe.
#
# Usage:
#   scripts/short-video/kaggle/push-build-kernel.sh [-t SECONDS] [--accelerator NONE]
#
# Extra arguments are forwarded to `kaggle kernels push`. As of kaggle-cli 2.2.4
# that command accepts only `-p/--path`, `-t/--timeout` and `--accelerator`
# (`kaggle kernels push --help`); argparse rejects anything else, so there is no
# dry-run flag to save a version without running it. An earlier revision of this
# comment claimed `--no-run` did that — it does not exist.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT="$HERE/build-wheels-dataset.sh"
MANIFEST="$HERE/wheelhouse-manifest.json"
KERNEL_ID="xPabloLI/231-build-wheels-dataset"

for f in "$SCRIPT" "$MANIFEST"; do
  [ -f "$f" ] || { echo "FAIL: missing $f" >&2; exit 1; }
done

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# The carrier kernel: install a current CLI, materialize both embedded files
# next to each other (build-wheels-dataset.sh looks for the manifest as its
# sibling), then run the build. The exit code is the kernel's.
HERE_FOR_PY="$HERE" WORK_FOR_PY="$WORK" python3 - <<'PY'
import base64, json, os, pathlib

here = pathlib.Path(os.environ["HERE_FOR_PY"])
work = pathlib.Path(os.environ["WORK_FOR_PY"])

script = here.joinpath("build-wheels-dataset.sh").read_text()
manifest = here.joinpath("wheelhouse-manifest.json").read_text()


def blob(text: str) -> str:
    return base64.b64encode(text.encode()).decode()


# Placeholders, not str.format: the carrier is Python full of braces (dicts,
# f-strings), and every one of them would have to be doubled to survive a
# format() call.
CARRIER = '''"""Build + publish the cosyvoice3-wheels dataset on Kaggle (#521).

GENERATED by scripts/short-video/kaggle/push-build-kernel.sh — do not edit.
The repo's build-wheels-dataset.sh and wheelhouse-manifest.json are embedded
below and stay the single source.
"""
import base64, os, subprocess, sys

subprocess.run([sys.executable, "-m", "pip", "install", "-q", "--upgrade", "kaggle"], check=True)

FILES = {
    "/kaggle/working/build-wheels-dataset.sh": "@@SCRIPT@@",
    "/kaggle/working/wheelhouse-manifest.json": "@@MANIFEST@@",
}
for path, payload in FILES.items():
    with open(path, "w") as f:
        f.write(base64.b64decode(payload).decode())
os.chmod("/kaggle/working/build-wheels-dataset.sh", 0o755)

# Kaggle's own disk is small; the 3.7GB wheelhouse needs the room that the
# working directory has.
os.environ["TMPDIR"] = "/kaggle/working/tmp"
os.makedirs(os.environ["TMPDIR"], exist_ok=True)

r = subprocess.run(["bash", "/kaggle/working/build-wheels-dataset.sh", "/kaggle/working/wheels"])
print("\\nbuild-wheels-dataset.sh exit:", r.returncode)
sys.exit(r.returncode)
'''.replace("@@SCRIPT@@", blob(script)).replace("@@MANIFEST@@", blob(manifest))

work.joinpath("build.py").write_text(CARRIER)
work.joinpath("kernel-metadata.json").write_text(
    json.dumps(
        {
            "id": "xPabloLI/231-build-wheels-dataset",
            "title": "231-build-wheels-dataset",
            "code_file": "build.py",
            "language": "python",
            "kernel_type": "script",
            "is_private": True,
            "enable_gpu": False,
            "enable_internet": True,
            "dataset_sources": [],
            "competition_sources": [],
            "kernel_sources": [],
            "model_sources": [],
        },
        indent=2,
    )
    + "\n"
)
print(f"carrier written: {work}")
PY

echo "==> pushing $KERNEL_ID"
kaggle kernels push -p "$WORK" "$@"
echo "==> watch: kaggle kernels status $KERNEL_ID"
