export const meta = {
  subject: "zhipu",
  pipelineId: "zhipu-glm6-self-training",
  title: "Zhipu AI Reveals GLM-6.0: Fully Self-Training",
  article: "zhipu-glm6-self-training",
  createdAt: "2026-09-02",
  topics: [
    "zhipu",
    "glm",
    "self-training",
    "agi",
    "coding",
    "national-chips",
    "tang-jie",
    "liu-debin",
  ],
  keyEntities: {
    companies: ["zhipu", "openrouter", "opencode"],
    people: ["tang_jie", "liu_debin"],
    models: ["glm_5_3", "glm_5_3_flash", "glm_6_0"],
  },
  dataPoints: [
    "GLM-6.0 first disclosed",
    "Fully self-training (RSI)",
    "Revenue up 400% YoY",
    "ARR $1.6B",
    "API revenue 86.5% of total",
    "Intelligence index 32 to 60",
    "GLM-5.3 Flash $0.045 per task",
    "100K domestic chips",
    "80% inference cost reduction",
    "CyberGym 84.5%",
    "2,436 vulnerabilities found",
    "7.4M registered users",
  ],
  hashtags: [
    "#ainews",
    "#chinaainews",
    "#zhipu",
    "#glm",
    "#agi",
  ],
};