export const meta = {
  subject: "kimi",
  pipelineId: "kimi-ipo",
  title: "Kimi's $50B IPO",
  article: "kimi-moonshot-ipo-50b",
  renderer: "remotion",
  createdAt: "2026-09-03",
  topics: ["kimi", "moonshot", "ipo", "china-ai", "ai-funding", "cloud", "open-weight", "us-china"],
  keyEntities: {
    companies: ["moonshot", "microsoft", "amazon", "google", "anthropic", "openai"],
    people: ["yang_zhilin", "scott_bessent"],
    models: ["kimi_k3", "gpt_5_5", "claude_opus_4_8"],
  },
  dataPoints: [
    "$50B target IPO valuation (Moonshot, Jul 2026)",
    "$3.5B F round raised, valuation $35B to $50B",
    "Valuation 7x in 6 months",
    "2.8T parameter Kimi K3 model",
    "30% cloud revenue share asked from Microsoft, Amazon, Google",
    "Founded April 2023, 3 years to IPO",
    "K3 matches GPT-5.5 and Claude Opus 4.8 (Artificial Analysis)",
    "US Treasury considering trade blacklist (Jul 22)",
    "K3 cost ~1/3 of Anthropic Fable",
    "K3 license: $20M MaaS revenue triggers renegotiation",
  ],
  trendingChecked: true,
  trendingHashtags: [],
};
