export const meta = {
  subject: "unitree",
  pipelineId: "unitree-ipo-debut",
  title: "Unitree IPO Pops 629%: China's First Robot Stock Is Here",
  article: "unitree-ipo-debut",
  createdAt: "2026-08-19",
  topics: ["Unitree", "humanoid robots", "IPO", "China robotics", "embodied AI"],
  keyEntities: {
    companies: ["unitree", "deepseek", "agibot", "tencent"],
    people: ["wang_xingxing", "liang_wenfeng"],
    models: [],
  },
  dataPoints: [
    "629% opening pop",
    "1100 yuan per share",
    "444.9B yuan market cap",
    "978 million retail investors",
    "0.0181% win rate",
    "8288x oversubscribed",
    "152 days IPO process",
    "219x P/E ratio",
    "5500+ humanoid shipments in 2025",
    "97% China global humanoid share",
    "Superman robot: 2m jump, 12.66m/s",
  ],
};
