/**
 * Issue #209: channel doctor — per-source access-channel inventory,
 * risk classification, cross-run health attachment, and probe outcomes.
 *
 * The layer chain (apiSearch → CDP → googleSiteFallback → apiFallback →
 * pool → mcpFallback) and the per-layer trajectory (#200) already route
 * and record fallbacks; the doctor's increment is a one-command inventory
 * of which channels each source actually has and which are degraded.
 */
import { describe, it, expect } from "vitest";
import {
  deriveChannels,
  classifyChannelRisk,
  attachSourceHealth,
  summarizeChannelInventory,
} from "../lib/channel-doctor.mjs";

const EMPTY_STUB = "var results = []; return results;";

const CDP_ONLY = {
  name: "zhihu",
  label: "知乎",
  category: "self_media",
  accessMethod: { primary: "cdp" },
  needsAuth: false,
  url: (kw) => `https://www.zhihu.com/search?q=${kw}`,
  articleScript: "var items = document.querySelectorAll('.card'); return results;",
};

const MCP_BACKED = {
  name: "weibo_hot",
  label: "微博热搜",
  category: "self_media",
  accessMethod: { primary: "cdp" },
  needsAuth: false,
  url: () => "https://s.weibo.com/top/summary",
  articleScript: "var items = document.querySelectorAll('td.td-02 a'); return results;",
  mcpFallback: {
    command: "python",
    args: ["-m", "mcp_server_weibo"],
    toolName: "get_hot_search",
  },
};

const TRACKED_FEED = {
  name: "wechat2rss_jiqizhixin",
  label: "机器之心",
  category: "wechat",
  accessMethod: { primary: "api" },
  needsAuth: false,
  sourceRole: "tracked-feed-context",
  url: () => "https://wechat2rss.xlab.app/feed/abc.xml",
  articleScript: EMPTY_STUB,
  apiSearch: { url: () => "https://wechat2rss.xlab.app/feed/abc.xml" },
  tracking: { access: "public-rss", freshnessWindowDays: 14 },
};

const API_WITH_MCP = {
  name: "xhs",
  label: "小红书",
  category: "self_media",
  accessMethod: { primary: "cdp" },
  needsAuth: true,
  url: (kw) => `https://www.xiaohongshu.com/search_result?keyword=${kw}`,
  articleScript: "var items = document.querySelectorAll('section.note-item'); return results;",
  apiFallback: { type: "http", model: "dots-chat" },
  mcpFallback: { command: "uvx", args: ["x"], toolName: "search_xhs" },
};

describe("deriveChannels", () => {
  it("reads the #88 auto-generated site: fallback from capabilities.articles", () => {
    const enriched = {
      ...CDP_ONLY,
      capabilities: {
        articles: {
          googleSiteFallback: { articleScript: "x", _autoGenerated: true },
        },
      },
    };
    const channels = deriveChannels(enriched);
    expect(channels.map((c) => c.type)).toEqual(["cdp", "google-site"]);
    expect(channels[1].detail).toBe("auto-generated site: search");
  });

  it("derives the CDP-only source as a single browser channel", () => {
    const channels = deriveChannels(CDP_ONLY);
    expect(channels).toHaveLength(1);
    expect(channels[0]).toMatchObject({ type: "cdp", primary: true });
  });

  it("ignores the empty articleScript stub (no real CDP channel)", () => {
    const channels = deriveChannels(TRACKED_FEED);
    expect(channels.map((c) => c.type)).toEqual(["api"]);
  });

  it("orders channels with the declared primary first", () => {
    const channels = deriveChannels(API_WITH_MCP);
    expect(channels.map((c) => c.type)).toEqual(["cdp", "api-fallback", "mcp"]);
    expect(channels[0].primary).toBe(true);
    expect(channels.slice(1).every((c) => !c.primary)).toBe(true);
  });

  it("records the mcp toolName and command for probe targeting", () => {
    const [, , mcp] = deriveChannels(API_WITH_MCP);
    expect(mcp).toMatchObject({ type: "mcp", toolName: "search_xhs", command: "uvx" });
  });
});

describe("classifyChannelRisk", () => {
  it("flags single-channel sources", () => {
    expect(classifyChannelRisk(CDP_ONLY)).toBe("single-channel");
  });

  it("treats tracked public feeds as their own low-risk class", () => {
    expect(classifyChannelRisk(TRACKED_FEED)).toBe("tracked-feed");
  });

  it("treats multi-channel sources as resilient", () => {
    expect(classifyChannelRisk(MCP_BACKED)).toBe("resilient");
  });
});

describe("attachSourceHealth", () => {
  it("attaches streaks and flags sources past the review threshold", () => {
    const inventory = [{ name: "zhihu" }, { name: "weibo_hot" }];
    const healthLog = {
      version: 1,
      sources: {
        zhihu: { consecutiveZeroRuns: 3, lastZeroAt: 1000, lastOkAt: null },
        weibo_hot: { consecutiveZeroRuns: 0, lastZeroAt: null, lastOkAt: 2000 },
      },
    };
    const out = attachSourceHealth(inventory, healthLog);
    expect(out.find((s) => s.name === "zhihu").health).toMatchObject({
      consecutiveZeroRuns: 3,
      review: true,
    });
    expect(out.find((s) => s.name === "weibo_hot").health).toMatchObject({
      consecutiveZeroRuns: 0,
      review: false,
    });
  });

  it("fills unknown health as fresh entries without review flags", () => {
    const out = attachSourceHealth([{ name: "xhs" }], null);
    expect(out[0].health).toMatchObject({ consecutiveZeroRuns: 0, review: false });
  });
});

describe("summarizeChannelInventory", () => {
  it("groups sources by risk class and surfaces the review list", () => {
    const sources = [CDP_ONLY, MCP_BACKED, TRACKED_FEED];
    const inventory = sources.map((s) => ({
      ...s,
      channels: deriveChannels(s),
      riskClass: classifyChannelRisk(s),
      health: { consecutiveZeroRuns: 0, review: s.name === "zhihu" },
    }));
    const summary = summarizeChannelInventory(inventory);
    expect(summary.totals).toEqual(
      expect.objectContaining({ "single-channel": 1, resilient: 1, "tracked-feed": 1 }),
    );
    expect(summary.review).toEqual(["zhihu"]);
  });
});
