export const meta = {
  subject: "deepseek",
  pipelineId: "deepseek-v41-flash-report",
  title: "DeepSeek V4.1 Flash Beats Pro on Agent Tasks",
  article: "deepseek-v41-flash-report",
  renderer: "remotion",
  createdAt: "2026-09-10",
  topics: ["deepseek", "v4-1-flash", "agent", "kv-cache", "ced-architecture", "china-ai", "llm", "api"],
  keyEntities: {
    companies: ["deepseek"],
    people: [],
    models: ["deepseek-v4-flash", "deepseek-v4-pro", "deepseek-v4-1-flash"],
  },
  dataPoints: [
    "V4.1 Flash released Sep 10, 2026; takes over V4 Pro API Sep 14 noon Beijing time at Flash pricing (DeepSeek tech report)",
    "DeepSWE v1.1: old Flash 54.4, old Pro 62.7, V4.1 Flash 74.2 (beats old Pro)",
    "Terminal-Bench 3.0: old Flash 7.6, old Pro 11.8, V4.1 Flash 30.0",
    "GPQA Diamond: old Flash 89.9, old Pro 92.4, V4.1 Flash 90.9 (barely moved)",
    "KV cache: 890 bytes/token, 1/4 of old Flash; persistent KV cache 1/8 of before",
    "Pricing: cached $0.006/M input, uncached $0.30/M (50x gap), output $1.20/M; off-peak half",
    "CED architecture: causal encoder + decoder, read/write split; 552B trunk, 8B input active / 16B output active",
    "196B Engram conditional memory parameters, fetched by lookup",
    "Training: million concurrent sandboxes on DSec platform + real failure traces",
    "Effort signal: low/high/max = 50/75/100; 60-80 effort gets most of max at <half output tokens",
    "Multi-agent: ProgramBench 172 tasks, 8h limit, multi-agent Almost@1 30.04% vs single 20.39%",
  ],
  hashtags: ["#chinaai", "#deepseek", "#ai", "#technews", "#chinatech"],
  trendingChecked: true,
  trendingNote: "Skipped web-access trending check; hashtags from analytics conclusions + brand defaults",
};