/**
 * Channel doctor (#209) — per-source access-channel inventory and health.
 *
 * Fallback routing itself lives in collectFromSource's layer chain and the
 * per-layer trajectory recorded into discovery.sourceHealth (#200); this
 * module is the inspection surface: derive which channels each source can
 * actually take, classify the ones with no fallback, attach cross-run
 * zero-result streaks (#200), and (CLI) probe what is cheaply probeable.
 *
 * Fail-open everywhere: doctor output must never break a discovery run.
 */
import { execFileSync } from "child_process";
import { REVIEW_THRESHOLD } from "./source-health.mjs";

/**
 * Empty articleScript stub used by api-first sources to keep the registry
 * contract while avoiding a real CDP scrape — not a channel.
 */
const EMPTY_SCRIPT_RE = /^var results = \[\];\s*return results;\s*;?$/;

/**
 * Derive the ordered access channels of one registry source.
 *
 * @param {object} source - registry source definition
 * @returns {Array<{type: string, detail: string, primary: boolean, probe: "http"|"browser"|"command", command?: string, toolName?: string}>}
 *   channels ordered so the declared primary (accessMethod.primary) comes first
 */
export function deriveChannels(source) {
  const channels = [];
  if (source.apiSearch) {
    let detail = "";
    try {
      detail = typeof source.apiSearch.url === "function" ? source.apiSearch.url() : String(source.apiSearch.url);
    } catch {
      detail = "(url unresolved)";
    }
    channels.push({ type: "api", detail, primary: source.accessMethod?.primary === "api", probe: "http" });
  }
  if (source.articleScript && !EMPTY_SCRIPT_RE.test(source.articleScript)) {
    let detail = "";
    try {
      detail = typeof source.url === "function" ? source.url("test") : String(source.url);
    } catch {
      detail = "(url unresolved)";
    }
    channels.push({ type: "cdp", detail, primary: source.accessMethod?.primary === "cdp", probe: "browser" });
  }
  // #88 auto-generated fallbacks live under capabilities.articles (explicit
  // source-level config stays on the source itself) — read both.
  const siteFallback =
    source.googleSiteFallback ?? source.capabilities?.articles?.googleSiteFallback;
  if (siteFallback) {
    channels.push({
      type: "google-site",
      detail: siteFallback._autoGenerated ? "auto-generated site: search" : "explicit site: search",
      primary: false,
      probe: "browser",
    });
  }
  if (source.apiFallback) {
    channels.push({
      type: "api-fallback",
      detail: `${source.apiFallback.type ?? "http"}:${source.apiFallback.model ?? "unknown"}`,
      primary: false,
      probe: "http",
    });
  }
  if (source.mcpFallback) {
    channels.push({
      type: "mcp",
      detail: `${source.mcpFallback.command} ${source.mcpFallback.toolName}`,
      primary: false,
      probe: "command",
      command: source.mcpFallback.command,
      toolName: source.mcpFallback.toolName,
    });
  }
  return channels.sort((a, b) => Number(b.primary) - Number(a.primary));
}

/**
 * Classify the fallback risk of a source from its channel shape.
 *
 * @returns {"tracked-feed"|"resilient"|"single-channel"|"no-channel"}
 */
export function classifyChannelRisk(source) {
  if (source.sourceRole === "tracked-feed-context") return "tracked-feed";
  const count = deriveChannels(source).length;
  if (count >= 2) return "resilient";
  if (count === 1) return "single-channel";
  return "no-channel";
}

/**
 * Attach the cross-run zero-result streak (#200) to an inventory entry.
 *
 * @param {Array<object>} inventory - entries with at least {name}
 * @param {object|null} healthLog - parsed output/source-health.json (null = fresh)
 * @returns {Array<object>} same entries with `health` added
 */
export function attachSourceHealth(inventory, healthLog) {
  return (inventory ?? []).map((entry) => {
    const record = healthLog?.sources?.[entry.name] ?? {};
    const consecutiveZeroRuns = record.consecutiveZeroRuns ?? 0;
    return {
      ...entry,
      health: {
        consecutiveZeroRuns,
        lastOkAt: record.lastOkAt ?? null,
        lastZeroAt: record.lastZeroAt ?? null,
        review: consecutiveZeroRuns >= REVIEW_THRESHOLD,
      },
    };
  });
}

/**
 * Aggregate the inventory into the doctor summary: per-risk-class totals and
 * the list of sources flagged for manual review.
 *
 * @param {Array<object>} inventory - entries with riskClass + health
 * @returns {{totals: Record<string, number>, review: string[]}}
 */
export function summarizeChannelInventory(inventory) {
  const totals = {};
  const review = [];
  for (const entry of inventory ?? []) {
    totals[entry.riskClass] = (totals[entry.riskClass] ?? 0) + 1;
    if (entry.health?.review) review.push(entry.name);
  }
  return { totals, review };
}

/**
 * Probe the cheaply probeable channels of one inventory entry.
 *
 * - command: checks the MCP host binary exists on PATH (module availability
 *   is NOT verified — spawning each MCP server would be far too heavy).
 * - http (live mode only): GET with a short timeout; records the status and
 *   a blocked flag for 403/429.
 * - browser: never probed — needs a logged-in CDP session, reported as unprobed.
 *
 * @param {object} entry - inventory entry with channels
 * @param {object} [opts]
 * @param {boolean} [opts.live=false] - also HTTP-probe api/api-fallback channels
 * @param {number} [opts.timeoutMs=8000]
 * @returns {Promise<object>} entry with `probes` added per channel
 */
export async function probeChannels(entry, opts = {}) {
  const { live = false, timeoutMs = 8000 } = opts;
  const probes = [];
  for (const channel of entry.channels ?? []) {
    const probe = { type: channel.type, status: "unprobed" };
    if (channel.probe === "command" && channel.command) {
      try {
        execFileSync("which", [channel.command], { stdio: "pipe" });
        probe.status = "command-available";
      } catch {
        probe.status = "command-missing";
      }
    } else if (channel.probe === "http" && live && channel.detail.startsWith("http")) {
      try {
        const resp = await fetch(channel.detail, {
          signal: AbortSignal.timeout(timeoutMs),
          headers: { "User-Agent": "Mozilla/5.0 (channel-doctor; inside-china-ai)" },
        });
        probe.status = resp.ok ? "ok" : "http-error";
        probe.httpStatus = resp.status;
        probe.blocked = resp.status === 403 || resp.status === 429;
      } catch (e) {
        probe.status = e?.name === "TimeoutError" ? "timeout" : "unreachable";
      }
    }
    probes.push(probe);
  }
  return { ...entry, probes };
}
