/**
 * ASS serialisation and parsing for word-level karaoke subtitles.
 *
 * Every word is anchored with `\kt` — an absolute offset from the line start —
 * instead of relying on consecutive `\k` durations. libass accumulates karaoke
 * time across a line (`ass_process_karaoke_effects`: `timing = tm_end + skip`),
 * so with plain `\k` the rounding error of each word is inherited by every word
 * after it. `\kt` sets `reset_effect`, which zeroes that accumulator, making
 * each word's timing independent of its neighbours.
 *
 * Karaoke arguments are parsed by libass with `argtod` and multiplied by 10 to
 * get milliseconds, so a fractional centisecond like `\kt6.7` is valid and
 * gives 1ms resolution. Integer centiseconds would quantise to 10ms.
 *
 * `\kt` is a v4++/libass tag. Old VSFilter builds ignore it, so the generated
 * .ass is a render-time artifact for our FFmpeg/libass burn-in, not a portable
 * delivery format.
 */

/** Unspoken words (SecondaryColour) — near-white, legible on the dark stage. */
export const COLOR_UNSPOKEN = "&H00F5F5F5";
/** Spoken words (PrimaryColour) — Dispatch Blue #4d8bff, the DESIGN.md progress marker. */
export const COLOR_SPOKEN = "&H00FF8B4D";

const DEFAULT_STYLE = {
  fontName: "Helvetica Neue",
  fontSize: 42,
  primaryColor: COLOR_SPOKEN,
  secondaryColor: COLOR_UNSPOKEN,
  outlineColor: "&H66000000",
  backColor: "&H66000000",
  outline: 3,
  shadow: 1,
  marginL: 65,
  marginR: 65,
  marginV: 450,
};

/**
 * Format seconds as an ASS timestamp (`h:mm:ss.cc`, centisecond resolution).
 *
 * @param {number} seconds
 * @returns {string}
 */
export function formatAssTime(seconds) {
  const totalCs = Math.max(0, Math.round(seconds * 100));
  const cs = totalCs % 100;
  const totalSeconds = (totalCs - cs) / 100;
  const s = totalSeconds % 60;
  const m = Math.floor(totalSeconds / 60) % 60;
  const h = Math.floor(totalSeconds / 3600);
  const pad = (n) => String(n).padStart(2, "0");
  return `${h}:${pad(m)}:${pad(s)}.${pad(cs)}`;
}

/** Centiseconds, rounded to 1 decimal (1ms) and printed without trailing zeros. */
function formatCs(seconds) {
  const cs = Math.max(0, Math.round(seconds * 1000) / 10);
  return Number.isInteger(cs) ? String(cs) : cs.toFixed(1);
}

function escapeText(text) {
  // Backslash first: the later rules introduce backslashes of their own, which
  // must not be re-escaped.
  return text
    .replace(/\\/g, "\\\\")
    .replace(/\{/g, "\\{")
    .replace(/\}/g, "\\}")
    .replace(/\r?\n/g, "\\N");
}

/**
 * Build the karaoke-tagged text for one cue.
 *
 * @param {{start: number, words: Array<{text: string, start: number, end: number}>}} cue
 * @returns {string}
 */
function karaokeText(cue) {
  // libass measures karaoke offsets from the event's Start, which only has
  // centisecond resolution — anchor against the value we actually write out.
  const lineStart = Math.round(cue.start * 100) / 100;

  return cue.words
    .map((word, index) => {
      const offset = formatCs(Math.max(word.start - lineStart, 0));
      const fill = formatCs(Math.max(word.end - word.start, 0));
      const spacer = index < cue.words.length - 1 ? " " : "";
      return `{\\kt${offset}\\kf${fill}}${escapeText(word.text)}${spacer}`;
    })
    .join("");
}

/**
 * Render cues as an ASS v4+ subtitle file.
 *
 * @param {Array<{start: number, end: number, text: string, words: Array}>} cues
 * @param {Partial<typeof DEFAULT_STYLE>} [styleOverrides]
 * @returns {string}
 */
export function renderAss(cues, styleOverrides = {}) {
  const style = { ...DEFAULT_STYLE, ...styleOverrides };

  const lines = [
    "[Script Info]",
    "; Generated by scripts/short-video/lib/subtitles/ass.mjs",
    "ScriptType: v4.00+",
    "PlayResX: 1080",
    "PlayResY: 1920",
    "WrapStyle: 0",
    "ScaledBorderAndShadow: yes",
    "",
    "[V4+ Styles]",
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
    `Style: Default,${style.fontName},${style.fontSize},${style.primaryColor},${style.secondaryColor},${style.outlineColor},${style.backColor},-1,0,0,0,100,100,0,0,1,${style.outline},${style.shadow},2,${style.marginL},${style.marginR},${style.marginV},1`,
    "",
    "[Events]",
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
  ];

  for (const cue of cues ?? []) {
    const text = cue.words?.length > 0 ? karaokeText(cue) : escapeText(cue.text ?? "");
    lines.push(
      `Dialogue: 0,${formatAssTime(cue.start)},${formatAssTime(cue.end)},Default,,0,0,0,,${text}`,
    );
  }

  return `${lines.join("\n")}\n`;
}

function parseAssTime(stamp) {
  const match = /^(\d+):(\d{2}):(\d{2})[.:](\d{2})$/.exec(stamp.trim());
  if (!match) return null;
  const [, h, m, s, cs] = match;
  return Number(h) * 3600 + Number(m) * 60 + Number(s) + Number(cs) / 100;
}

/**
 * Split a Dialogue payload into karaoke tag blocks and literal text runs.
 *
 * Handles libass's `\{` / `\}` literal-brace extension, so an escaped brace in
 * the subtitle text is not mistaken for the start of an override block.
 */
function tokenizeDialogueText(raw) {
  const tokens = [];
  let literal = "";
  let i = 0;

  const flushLiteral = () => {
    if (literal) {
      tokens.push({ type: "text", value: literal });
      literal = "";
    }
  };

  while (i < raw.length) {
    const char = raw[i];
    const next = raw[i + 1];

    if (char === "\\" && next === "\\") {
      literal += "\\";
      i += 2;
      continue;
    }
    if (char === "\\" && (next === "{" || next === "}")) {
      literal += next;
      i += 2;
      continue;
    }
    if (char === "\\" && (next === "N" || next === "n")) {
      literal += "\n";
      i += 2;
      continue;
    }
    if (char === "\\" && next === "h") {
      literal += " ";
      i += 2;
      continue;
    }
    if (char === "{") {
      const close = raw.indexOf("}", i + 1);
      if (close === -1) {
        literal += raw.slice(i);
        break;
      }
      flushLiteral();
      tokens.push({ type: "tags", value: raw.slice(i + 1, close) });
      i = close + 1;
      continue;
    }

    literal += char;
    i += 1;
  }

  flushLiteral();
  return tokens;
}

/**
 * Parse an ASS file back into cues with absolute word onsets.
 *
 * Applies libass's karaoke clock semantics: `\k`/`\kf` advance the clock by
 * their duration, `\kt` resets it to an absolute offset from the line start.
 *
 * @param {string} content
 * @returns {Array<{start: number, end: number, text: string, words: Array<{text: string, onset: number, fill: number}>}>}
 */
export function parseAss(content) {
  const cues = [];

  for (const line of (content ?? "").split(/\r?\n/)) {
    if (!line.startsWith("Dialogue:")) continue;

    const fields = line.slice("Dialogue:".length).split(",");
    if (fields.length < 10) continue;

    const start = parseAssTime(fields[1]);
    const end = parseAssTime(fields[2]);
    if (start === null || end === null) continue;

    const payload = fields.slice(9).join(",");
    const tokens = tokenizeDialogueText(payload);

    const words = [];
    let clock = 0;
    let pending = null;

    for (const token of tokens) {
      if (token.type === "tags") {
        const absolute = /\\kt(-?[\d.]+)/.exec(token.value);
        const fill = /\\(?:kf|ko|K|k)(-?[\d.]+)/.exec(token.value);
        // A karaoke run with no glyphs still consumes its duration.
        if (fill && pending) {
          clock = pending.onset + pending.fill;
          pending = null;
        }
        if (absolute) clock = Number(absolute[1]) / 100;
        if (fill) pending = { onset: clock, fill: Number(fill[1]) / 100 };
        continue;
      }

      const text = token.value.trim();
      if (pending) {
        if (text) words.push({ text, onset: start + pending.onset, fill: pending.fill });
        clock = pending.onset + pending.fill;
        pending = null;
      }
    }

    const text = tokens
      .filter((t) => t.type === "text")
      .map((t) => t.value)
      .join("")
      .trim();

    cues.push({ start, end, text, words });
  }

  return cues;
}
