/**
 * AvatarCard fixture composition (#214 ticket 02).
 *
 * Dedicated entry point with its own registerRoot — Root.tsx is never
 * touched. Driven by __tests__/avatar-card-render.test.mjs via `remotion
 * still` to prove the digital-human foreground card against a real Chromium
 * render runtime (same driver pattern as scene-gate-fixture.tsx).
 *
 * Scenarios (spec Behavioral Scenarios 1/2 + ticket acceptance criteria):
 *   avatar-card    — CTA scene with a fully-declared avatar: the card must
 *                    appear at the right-center rect from lib/safe-zones.mjs
 *   avatar-present — same scene with present: [{from:1, to:3}]: card visible
 *                    only inside the window; boundary frames render exactly
 *                    like the control (no residue on the switch frames)
 *   avatar-control — identical scene WITHOUT the avatar field: the pixel
 *                    baseline the other two are diffed against (zero-regression)
 *
 * videoPath is the public/assets/ BASENAME (the form stageAvatarVideos()
 * writes into props); the fixture video itself is generated at test time by
 * the driver (ffmpeg testsrc2 @1248×1632 — the 2x-upscaled EchoMimicV3 frame
 * size) and cleaned up afterwards.
 */
import React from "react";
import { Composition, registerRoot } from "remotion";
import { FPS } from "./components/shared";
import { ShortVideo } from "./ShortVideo";
import type { SceneData } from "./types";

/** Fixture clip basename, generated by the test driver into public/assets/. */
export const AVATAR_FIXTURE_VIDEO = "avatar-card-fixture.mp4";

const CTA_BASE: SceneData = {
  id: 6,
  name: "cta",
  visualType: "cta",
  voiceover: "Follow for more China AI news that matters.",
  texts: {
    brand: "CHINA AI NEWS",
    brandHighlight: "AI",
    tagline: "DAILY CHINA AI BRIEFING",
    action: "FOLLOW FOR MORE",
    topic: "QWEN4 WATCH",
  },
};

const AVATAR_SCENE: SceneData = {
  ...CTA_BASE,
  avatar: { videoPath: AVATAR_FIXTURE_VIDEO, position: "right-card" },
};

const AVATAR_PRESENT_SCENE: SceneData = {
  ...CTA_BASE,
  avatar: {
    videoPath: AVATAR_FIXTURE_VIDEO,
    position: "right-card",
    present: [
      { from: 1, to: 3 },
    ],
  },
};

type FixtureProps = { scenario?: string };

const FixtureScene: React.FC<FixtureProps> = ({ scenario = "avatar-card" }) => {
  if (scenario === "avatar-card") {
    return <ShortVideo scenes={[AVATAR_SCENE]} audioPaths={[]} durations={[4]} />;
  }
  if (scenario === "avatar-present") {
    return <ShortVideo scenes={[AVATAR_PRESENT_SCENE]} audioPaths={[]} durations={[4]} />;
  }
  if (scenario === "avatar-control") {
    return <ShortVideo scenes={[CTA_BASE]} audioPaths={[]} durations={[4]} />;
  }
  throw new Error(`Unknown avatar-card fixture scenario: ${scenario}`);
};

export const AvatarCardFixtureRoot: React.FC = () => (
  <Composition
    id="AvatarCardFixture"
    component={FixtureScene as unknown as React.FC<Record<string, unknown>>}
    durationInFrames={150}
    fps={FPS}
    width={1080}
    height={1920}
    defaultProps={{ scenario: "avatar-card" }}
  />
);

registerRoot(AvatarCardFixtureRoot);
