/**
 * MediaBackground videoStartOffsetMs fixture (#360 ticket-2).
 *
 * Dedicated entry point with its own registerRoot — Root.tsx is never
 * touched. Driven by __tests__/media-start-offset.test.mjs via
 * `remotion still` to prove the offset start behavior against a real
 * Chromium render runtime (same driver pattern as avatar-card-fixture.tsx).
 *
 * Scenarios (spec S6/S7/S8):
 *   offset-0           — no videoStartOffsetMs: playback starts at source
 *                        frame 0 (the regression baseline)
 *   offset-5000        — videoStartOffsetMs: 5000: playback starts at
 *                        source t=5s (frame 15 shows source t≈5.5s)
 *   offset-out-of-range — videoStartOffsetMs: 120000 on a 12s source:
 *                        beyond the source end — must NOT crash the render
 *
 * The fixture clip is generated at test time (ffmpeg testsrc2, 12s of
 * moving content) into public/assets/ and deleted afterwards — no
 * committed binaries.
 */
import React from "react";
import { AbsoluteFill, Composition, registerRoot } from "remotion";
import { MediaBackground } from "./components/MediaBackground";
import type { MediaField } from "./types";

/** Fixture clip basename, generated by the test driver into public/assets/. */
export const MEDIA_OFFSET_FIXTURE_VIDEO = "media-offset-fixture.mp4";

const BASE_MEDIA: MediaField = {
  type: "video",
  path: `assets/${MEDIA_OFFSET_FIXTURE_VIDEO}`,
  animation: "none", // static envelope — pixel diffs isolate the offset
  volume: 0,
};

type FixtureProps = { scenario?: string };

const FixtureScene: React.FC<FixtureProps> = ({ scenario = "offset-0" }) => {
  const media: MediaField =
    scenario === "offset-5000"
      ? { ...BASE_MEDIA, videoStartOffsetMs: 5000 }
      : scenario === "offset-out-of-range"
        ? { ...BASE_MEDIA, videoStartOffsetMs: 120000 }
        : BASE_MEDIA;
  return (
    <AbsoluteFill style={{ background: "#000" }}>
      <MediaBackground media={media} duration={4} />
    </AbsoluteFill>
  );
};

export const MediaOffsetFixtureRoot: React.FC = () => (
  <Composition
    id="MediaOffsetFixture"
    component={FixtureScene as unknown as React.FC<Record<string, unknown>>}
    durationInFrames={300}
    fps={30}
    width={1080}
    height={1920}
    defaultProps={{ scenario: "offset-0" }}
  />
);

registerRoot(MediaOffsetFixtureRoot);
