export const meta = {
  subject: "alibaba-ai-megabet",
  pipelineId: "alibaba-ai-megabet",
  title: "Alibaba's $10B AI Megabet",
  article: "alibaba-80b-ai-megabet",
  renderer: "remotion",
  createdAt: "2026-08-25",
  topics: ["alibaba", "china-ai", "ai-investment", "cloud", "qwen"],
  keyEntities: {
    companies: ["alibaba"],
    people: ["jack-ma", "eddie-wu", "joe-tsai"],
    models: ["qwen"],
  },
  dataPoints: [
    "80 billion HKD share placement ($10.2B)",
    "100% allocated to AI infrastructure",
    "First equity offering since 2019 HK listing",
    "3x oversubscribed by sovereign wealth funds",
    "Net cash from $31B to $41B+",
    "Alibaba Cloud revenue up 45% YoY",
    "AI product revenue 12.376B RMB, 12th quarter of triple-digit growth",
    "Capex 67.678B RMB, up 75% YoY",
    "CEO: AI capex payback in 3 years, targeting 2 years",
    "Next quarter AI ARR approaching $10B",
    "Goal: $100B cloud revenue by 2030",
    "T-Head chips supporting 650+ enterprises",
    "Alibaba Cloud #1 in APAC, #2 globally by growth",
    "Qwen downloads #1 globally",
  ],
  trendingChecked: true,
  trendingHashtags: [],
};
