export const meta = {
  subject: "deepseek",
  pipelineId: "deepseek-harness-desktop",
  title: "DeepSeek's Desktop App Leaked Five Days Before Launch",
  article: "deepseek-harness-desktop",
  renderer: "remotion",
  createdAt: "2026-09-29",
  topics: [
    "deepseek",
    "deepseek-harness",
    "desktop-app",
    "ai-agents",
    "plugins",
    "china-ai",
    "coding-agent",
  ],
  keyEntities: {
    companies: ["deepseek"],
    people: [],
    models: ["deepseek-harness", "deepseek-v4-1-flash", "cordis"],
  },
  dataPoints: [
    "Desktop installers for macOS (Apple silicon) and Windows 64-bit live on deepseek.com/harness (DeepSeek, Sept 29, 2026)",
    "Announcement posted Sept 29, 2026 at 20:04 China time by the DeepSeek Harness team",
    "Signed installers were already circulating from Sept 24 with no announcement (36Kr, Sina Finance, iFeng)",
    "GitHub tags: dsh-v0.1.7-rc.1 Sept 23, rc.2 Sept 24, dsh-v0.2.0-rc.1 Sept 28, rc.2 Sept 29 09:42 UTC",
    "Plugin management page installs by npm package name, no command line",
    "Client is MIT licensed and open source, built on the Cordis everything-is-a-plugin architecture",
    "About 60% of DeepSeek Harness users run a third-party plugin (official API user base, DeepSeek telemetry)",
    "Creator mode is experimental: describe a plugin, the app writes and installs it",
    "Official demo builds a Pomodoro timer plugin in 5 minutes 24 seconds",
    "Launch credit: 6 yuan (about $0.89), limited quantity, valid 7 days, +86 registration rules apply",
    "DeepSeek estimate: 6 yuan covers about 120 million cache-hit input tokens at off-peak V4.1 Flash prices",
    "36Kr hands-on: first run needs a funded account or API key plus real-name verification",
    "Roadmap: sandbox and security, agent teams, long-term memory, browser and GUI automation, remote and mobile, session sharing",
    "DeepSeek says it will optimize model performance inside Harness during model training",
  ],
  hashtags: ["#deepseek", "#chinaai", "#aiagents", "#aitools", "#codingagent"],
};
